# Generated by Django 5.0.7 on 2024-07-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(default='Category/default.jpg', upload_to='Category/'),
        ),
    ]
